{
 "title": "Teste Infinispan",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "jobs", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "Instance", "label": "Instancia", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load JVM (\"$jobs\")",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad{job=~\"$jobs\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "base_cpu_processCpuLoad_percent{job=~\"$jobs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads JVM (\"$jobs\")",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_thread_daemon_count{job=~\"$jobs\"}",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM NonHeapMemory Commited ($jobs)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_memory_committedNonHeap_bytes{job=~\"$jobs\"}",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM HeapMemory Commited",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_memory_committedHeap_bytes{job=~\"$jobs\"}",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM HeapMemory Used ($jobs)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{job=~\"$jobs\"}",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM NonHeapMemory Used ($jobs)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_memory_usedNonHeap_bytes{job=~\"$jobs\"}",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  { "title": "Cache Container ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Cache Container Memory Used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_container_health_total_memory_kb{job=~\"$jobs\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "BufferPool Used Memory",
   "type": "stat",
   "description": "The memory used by the NIO pool: direct",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_BufferPool_used_memory_direct_bytes{job=~\"$jobs\"}",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used - Cliente",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_statistics_data_memory_used{job=~\"$jobs\"}",
     "legendFormat": "data-{{node}}"
    },
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_statistics_off_heap_memory_used{job=~\"$jobs\"}",
     "legendFormat": "off-heap-{{node}}"
    }
   ]
  },
  {
   "title": "Cache Container Average Read Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_container_stats_average_read_time_nanos",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cache container Average Write Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_container_stats_average_write_time_nanos",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cache Container Average Remove Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_container_stats_average_remove_time_nanos",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cliente Average Read Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_statistics_average_read_time_nanos",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cliente Average Write Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_statistics_average_write_time_nanos",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cliente Average Store Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_statistics_store_times_mean_seconds",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Salario-Temp Average Read Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_salario_temp_statistics_average_read_time_nanos",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Salario-Temp Average Write Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_salario_temp_statistics_average_write_time_nanos",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cliente Average Remove Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_statistics_average_remove_time_nanos",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cliente - Itens",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_cliente_cluster_cache_stats_number_of_entries",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Salario - Itens",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_salario_temp_cluster_cache_stats_number_of_entries",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Salario-Temp Average Remove Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "vendor_cache_manager_meu_infinispan_cache_salario_temp_statistics_average_remove_time_nanos",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Camel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Camel - RouteExchanges Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "application_camel_route_exchanges_completed_total",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel - RouteExchanges Failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "application_camel_route_exchanges_failed_total",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel - RouteExchanges FailureHandled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "application_camel_route_failuresHandled_total",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel - RouteExchanges ReDelivered",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "application_camel_route_externalRedeliveries_total",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel - RouteExchanges Total",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_exchanges_total",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel - Rotas - exchange p/segundo",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_processing_rate_per_second",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel - Rotas - excanges infligit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "application_camel_route_exchanges_inflight_count",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel - MAX exchange p/segundo",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Max(application_camel_route_processing_rate_per_second) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  }
 ]
}