global:
  scrape_interval:     15s
  evaluation_interval: 15s

# rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']  
  
  - job_name: kml2infinispan
    metrics_path: /q/metrics
    static_configs:
      - targets: ['0.0.0.0:8092']

  - job_name: dg-cache-monitor
    metrics_path: /q/metrics
    static_configs:
      - targets: 
        - 0.0.0.0:8087

  - job_name: infinispan
    basic_auth:
      username: 'admin'
      password: 'password'
    # authorization:
    #   type: digest
    static_configs:
      - targets: ['0.0.0.0:11222', '0.0.0.0:11223' ] 
